### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by defininja** [family/connectkit#249] opened 2023-06-26 13:21 UTC
**Installed connectkit with yarn in react+typescript but unable to use it within the app.js file**

Tried to use connectkit + wagmi for creating a web3 wallet connect for a application but the module is not getting recognised on running the application. 

Using connectkit version 1.4.0
wagmi version 1.3.0
viem version 1.1.7

A CodeSandbox (preferably) 
<img width="591" alt="Screenshot 2023-06-26 at 6 45 16 PM" src="https://github.com/family/connectkit/assets/91393134/21c43863-b0dc-4122-8ed2-e77169f2a674">
or specify which version of ConnectKit you're using along with reproduction steps.

**Expected behavior**

**Screenshots**

{
  "name": "aqua-farm",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@binance-chain/bsc-connector": "^1.0.0",
    "@ethersproject/units": "^5.4.0",
    "@fortawesome/fontawesome-svg-core": "6.x",
    "@fortawesome/free-solid-svg-icons": "6.x",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@intract/attribution": "^1.2.4",
    "@metamask/detect-provider": "^1.2.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "@types/react-modal": "^3.16.0",
    "@types/react-rangeslider": "^2.2.3",
    "@types/react-redux": "^7.1.16",
    "@types/react-router": "^5.1.13",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-tooltip": "^4.2.4",
    "@types/styled-components": "^5.1.9",
    "@walletconnect/web3-provider": "1.3.4",
    "@web3modal/ethereum": "^2.6.0",
    "@web3modal/react": "^2.6.0",
    "axios": "^0.21.1",
    "bignumber.js": "^9.0.1",
    "connectkit": "^1.4.0",
    "eth-permit": "^0.1.9",
    "moment": "^2.29.1",
    "react": "^18.2.0",
    "react-countup": "^6.1.1",
    "react-dom": "^18.2.0",
    "react-modal": "^3.16.1",
    "react-rangeslider": "^2.2.0",
    "react-redux": "^7.2.3",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.3",
    "react-tooltip": "^4.2.21",
    "recharts": "^2.1.9",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.4.1",
    "styled-components": "^5.2.3",
    "typescript": "4.2.3",
    "viem": "^1.1.8",
    "wagmi": "^1.3.1",
    "web-vitals": "^1.0.1",
    "web3": "1.2.11",
    "web3modal": "^1.9.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
  },
  "devDependencies": {
    "react-error-overlay": "6.0.9"
  },
  "resolutions": {
    "//": "See https://github.com/facebook/create-react-app/issues/11773",
    "react-error-overlay": "6.0.9"
  }
}

If applicable, let us know which OS, browser, browser version etc you're using.

**Additional context**

**Comment by lochie** [comment] 2023-06-28 07:38
@defininja could you create a codesandbox that replicates this issue? I couldn't reproduce this.

**Comment by lochie** [comment] 2023-07-17 03:01
Closing for now while awaiting a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Feel free to reopen at that time.

**Closed by lochie** 2023-07-17 03:01 UTC
Labels: bug
