### ISSUE TITLE
[BUG] Error while importing ConnectKitButton 

### ISSUE THREAD

**Issue by vinayakathavale** [family/connectkit#15] opened 2022-10-01 14:51 UTC
**Describe the bug**
Error while importing ConnectKitButton.

When i import ConnectKitButton in react with `import { ConnectKitButton } from 'connectkit';`
 I get the following error.
`Failed to compile.

./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
`

**To reproduce**
im getting the error with both v0.0.1 and 0.0.2 of connectkit
"react": "^18.0.1",
"wagmi": "^0.6.7",

**Expected behavior**
No error when things are imported

**Screenshots**

**Environment details**
MacOS, firefox 
If applicable, let us know which OS, browser, browser version etc you're using.

**Additional context**

**Comment by lochie** [comment] 2022-10-03 00:07
Hey @vinayakathavale,

It looks like some build environments (like create-react-app) might have some trouble mixing ES modules (`framer-motion`) and CJS modules. 
If your `tsconfig.json` file is using `"target": "es5"` a quick fix that might work is to update to `"target": "es6"`, but ymmv.

Thanks for raising our attention on this, we'll look into a fix so this doesn't occur in future releases and will keep this issue open until we have a built-in fix for this.

**Comment by lochie** [comment] 2022-10-23 23:53
Hey @vinayakathavale, just following up on this. Did the above resolve your issue?

**Comment by lochie** [comment] 2022-11-06 23:27
This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Closed by lochie** 2022-11-06 23:27 UTC
Labels: bug

**Comment by 70nyIT** [comment] 2022-11-09 11:15
hi @lochie 
I'm havign same issue ( using `"connectkit": "^1.0.0",` ). I've tried also to add `"target": "es6"` but with no success

**Comment by 70nyIT** [comment] 2022-11-09 11:30
If this can be of any help, I've solved by upgrading to `"react-scripts": "5.0.1",` (previously was `4.x.x`)
