### ISSUE TITLE
[BUG] Prompted to "Install MetaMask" with MetaMask already installed

### ISSUE THREAD

**Issue by j6i** [family/connectkit#245] opened 2023-06-22 23:52 UTC
**Describe the bug**

While connecting through MetaMask, I'm prompted to install MetaMask, but it's already installed. It looks like having Phantom installed causes this. Looks like Brave, Dawn, Tokenary, and Frame could also cause this issue.

**To reproduce**

Install the Phantom wallet, and try and connect on any connectkit implementation.

**Expected behavior**

To connect using MetaMask, without other wallet extensions affecting the experience.

**Screenshots**

![Screenshot 2023-06-22 at 16 41 49](https://github.com/family/connectkit/assets/43463199/3a5a3c15-4ccb-4f02-9ea4-1d499dc70c52)

**Environment details**

macOS v13.4.1 (22F82), Chrome v114.0.5735.133, latest version connectkit

**Additional context**

It looks like the cause is [this line here](https://github.com/family/connectkit/blob/main/packages/connectkit/src/utils/index.ts#L118)

**Comment by smitch88** [comment] 2023-06-23 15:30
Also seeing this issue, quite a bad user experience, as sometimes the "Browser Wallet" option doesn't come up either for some users

**Comment by j6i** [comment] 2023-06-23 20:36
> Also seeing this issue, quite a bad user experience, as sometimes the "Browser Wallet" option doesn't come up either for some users
> 
> Edit; @j6i, I set my dependencies to match connectkit directly, namely,
> 
> ```
> "viem": "~0.3.19",
> "wagmi": "^1.0.0"
> ```
> 
> and this actually does seem to work as expected

That makes sense, we use the latest versions of wagmi and viem.

I'll consider downgrading. Though it looks like there is a [PR](https://github.com/family/connectkit/pull/239) for the upgrade. Hopefully, that fixes the issue and I won't need to

**Comment by glitch-txs** [comment] 2023-06-26 06:49
This is done on purpose inside the MetaMask connector, if this is removed clicking on MetaMask to connect would popup Phantom wallet or other wallet instead. You need to set the config in Phantom wallet to use MetaMask as desired main wallet, for Brave you set this on browser config I think..

**Comment by pujux** [comment] 2023-07-01 10:26
I am also experiencing this with a few testers of my app. This is critical for me. 
@lochie is there any estimation on when this will be fixed? 
The package doesn't seem to work nicely with both MetaMask & Phantom installed. 

I'm fine with issuing a PR if we can have a chat on what you expect from the change, surely the best option would be to decouple them (if possible) and complete support for Phantom.

**Comment by wcjohnson11** [comment] 2023-07-28 17:26
The opening comment is correct that the issue is coming from the [`isMetamask` function](https://github.com/family/connectkit/blame/85d2964939653efe8fac2ee2c3cf04cd52f57665/packages/connectkit/src/utils/index.ts#L147).

With just metamask installed in the browser, it will pass the `return false` checks specific to Metamask and eventually [`return true`]() at the end of the function.

However, with any of the other wallets also installed in the same browser, it will `return false`  before getting to the end of the function where the `return true` is.

There is a [new PR that improves the Injected Connector Code](https://github.com/family/connectkit/pull/273), and i've left [a comment](https://github.com/family/connectkit/pull/273#discussion_r1277816680) because the issue is still present there.

**Comment by lochie** [comment] 2023-08-11 06:06
Hey gang! This should be fixed in ConnectKit `1.5.1`. Let us know if you find any issues 🫡

**Closed by lochie** 2023-08-11 06:06 UTC
Labels: bug
