### ISSUE TITLE
[BUG] connectkit (wagmi) is spamming alchemy

### ISSUE THREAD

**Issue by keon** [family/connectkit#33] opened 2022-10-22 16:12 UTC
<img width="1499" alt="Screen Shot 2022-10-23 at 01 09 24" src="https://user-images.githubusercontent.com/10793962/197349654-6b5a5209-2d0d-42d2-a0d0-475dc0bd6ef8.png">

connectkit is sending so many requests to alchemy that it sometimes exceeds concurrent requests limit.
You can easily recreate this by going into `https://docs.family.co/connectkit/try-it-out` and clicking connect, and going in and out of modals several times.

```
{"jsonrpc":"2.0","id":42,"error":{"code":429,"message":"Your app has exceeded its concurrent requests capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemyapi.io/documentation/rate-limits. Reach out to us if you'd like to increase your limits: https://dashboard.alchemyapi.io/support"}}
```

**Comment by charlycator** [comment] 2022-10-24 07:53
I'm having the same issue. Using wagmi and clicking and Alchemy and having same error

**Comment by charlycator** [comment] 2022-10-24 09:04
I think that maybe you haven't set well the Alchemy API Key. I saw that Alchemy is using it's own default PK and for that was not allowed. So I set tup well the Alchemy PK in the Alchemy configureChains method and everything works fine.

**Comment by MarcusHSmith** [comment] 2022-11-02 22:19
Same issue. Any solution yet?

**Comment by Neaxic** [comment] 2022-11-03 21:03
Same issue, it seems to be new? Went back to old deploys and the bug is still there.. I dont recall it being a problem then?

**Comment by Neaxic** [comment] 2022-11-03 21:08
I seem to have found a fix, I'm still not quite sure what caused this bug though.

In the configureChains hook, explicitly type your apikey in. - I was previously using my .env variable, but for some reason this fixed the spamming of api calls. - when it theory it should be the same.. Hope this works for some of you, like it did for me.

**Comment by Aayushd18** [comment] 2022-11-05 13:38
> I seem to have found a fix, I'm still not quite sure what caused this bug though.
> 
> In the configureChains hook, explicitly type your apikey in. - I was previously using my .env variable, but for some reason this fixed the spamming of api calls. - when it theory it should be the same.. Hope this works for some of you, like it did for me.

If you are using NextJS, try naming your env variables starting with NEXT_PUBLIC_ALCHEMY_ID instead of just ALCHEMY_ID.

**Comment by sshmatrix** [comment] 2022-11-07 04:56
I had the same issue with Next.js + wagmi + RainbowKit after updating packages to latest versions. Despite providing my own `apiKey` via `process.env.NEXT_PUBLIC_` and explicitly, `alchemyProvider` kept falling back to default public `apiKey`. The fix was to revert back a few versions on wagmi to 0.5.0 and RainbowKit to 0.4.0

**Comment by lochie** [comment] 2022-11-08 02:56
It sounds like some of you are experiencing missing Alchemy IDs in your configuration. Double check your env variables are written properly for your framework, Nextjs requires the `NEXT_PUBLIC_` prefix on all client-side variables.

If you are still finding issues I've written some potential debugging/fixing options over in issue https://github.com/family/connectkit/issues/36#issuecomment-1306551698

**Comment by levinunnink** [comment] 2022-11-08 16:24
Same as above. I can confirm that this is happening with a valid alchemy id. It's seems to just be spamming the service.

**Comment by johnpaulcas** [comment] 2022-11-08 22:00
experiencing this issue on wagmi using connectkit, any way to solve this issue from wagmi team?

**Comment by jterskine** [comment] 2022-11-09 03:02
Same here unfortunately. ConnectKit 1.0, have `stallTimeout`, `NEXT_PUBLIC_ALCHEMY_ID`. Let me know if need anything else for testing, :pray:

**Comment by johnpaulcas** [comment] 2022-11-09 05:49
> Same here unfortunately. ConnectKit 1.0, have `stallTimeout`, `NEXT_PUBLIC_ALCHEMY_ID`. Let me know if need anything else for testing, 🙏

hi @jterskine doing this configuration 

```
const { provider, webSocketProvider } = configureChains(
  supportedChain,
  [
    infuraProvider({ apiKey: infuraId, stallTimeout: 1_000, priority: 0 }),
    alchemyProvider({ apiKey: alchemyId, stallTimeout: 1_000, priority: 1 }),
    publicProvider({ priority: 2 })
  ]
)
```

**Comment by lochie** [comment] 2022-11-09 15:28
Hey everyone, I have some answers that will hopefully provide some help:

## Solutions
* Ensure your environment variables match your frameworks requirements (e.g [Next.js](https://create-react-app.dev/docs/adding-custom-environment-variables/) requires the `NEXT_PUBLIC_` prefix, while [create-react-app](https://nextjs.org/docs/basic-features/environment-variables) requires the `REACT_APP_` prefix), you can test by `console.log`ing out your env variables to double check that it's being returned correctly.
 * If you are unsure about your env variables setup, or are still having issues, feel free to supply your API key directly into the client configuration instead of env vars, as these variables are client-side anyway and the env var setup is more of a suggestion based on developer standards.
* Check you have whitelisted your domains within Infura/Alchemy's dashboards (don't forget `localhost`!)

## Why the 429 error
If your Infura/Alchemy key has not been passed through to the `WagmiClient` (or our `getDefaultClient`) correctly then wagmi will fall back to [an Alchemy provider that uses a shared public API key](https://wagmi.sh/docs/providers/public), in which has been severly rate limited (the 429 error).
For reference, the shared API key for wagmi `0.6.x` and below is `_gg7wSSi0KMBsdKnGVfHDueq6xMB9EkC` and can be [found in the wagmi codebase here](https://github.com/wagmi-dev/wagmi/blob/389765f7d9af063ab0df07389a2bbfbc10a41060/packages/core/src/constants/rpcs.ts#L3) (which you also can see in the error logs that are returning a 429 error).

If you have updated to wagmi `0.7.x` you may have noticed the 429 errors going away. The reason behind this is because this version of wagmi uses a different fallback API key, which although is also rate limited, not as many projects are using this version of wagmi – so at this point in time the new public wagmi key succeeds more often than the older version.

## Why the spamming
When Alchemy fails to receive data (i.e the 429 error) it has an auto-retry method baked into it. This auto-retry pings the API a few times a second until it receives data, which explains the spamming.
A valid API key supplied to the client configuration will stop this issue.

## Further debugging
You can check your apps client configurations by using the [useProvider hook ](https://wagmi.sh/docs/hooks/useProvider)and looking at the `providerConfigs` array to see what configured providers are available.
<img width="304" alt="CleanShot 2022-11-10 at 02 27 27@2x" src="https://user-images.githubusercontent.com/1930210/200871231-d0db414d-037e-4977-819b-ab8edc60bd3c.png">
 If you don't see your provider and API key in here then there may be a different issue with your client configuration. Feel free to open a ticket if this occurs.

I hope this helps resolve everyones issues.
There's also some conversations relating to this issue in https://github.com/family/connectkit/issues/36 if anyone else wants some further reading.

**Comment by rafinskipg** [comment] 2022-11-09 16:26
I found the problem.

The problem is rainbowkit induces people to use a ALCHEMY_ID but alchemy has one ID for each network!

So if you change network, you will start using the default provider again, it only works on the network you created the ID for.

**Comment by lochie** [comment] 2022-11-10 04:34
@rafinskipg if you're using RainbowKit please note that that is an entirely different SDK to ConnectKit.
Please reach out to them or file an issue on [their repo](https://github.com/rainbow-me/rainbowkit) rather than on ours.

**Comment by lochie** [comment] 2022-11-11 06:29
Closing this issue as we believe this isn't an issue with ConnectKit, but rather how Alchemy handles fallbacks.

If you are having issues please [read this comment](https://github.com/family/connectkit/issues/33#issuecomment-1308935780) to help resolve potential setup issues. If you are still having issues feel free to open a new ticket with an reproducible example to help us debug.

**Closed by lochie** 2022-11-11 06:29 UTC
Labels: bug

**Comment by johnnyshankman** [comment] 2023-01-05 00:35
Why can't you just provide no provider and allow them to bring their own via WalletConnect or MM etc? Why is this a required field?

**Comment by wesleyfsmith** [comment] 2023-03-08 15:51
I was able to fix this issue by making sure that the that the wagmiClient also has the websocketProvider being passed in, in addition to the regular provider. This makes sense to me, because we didn't have the issue until we started using useContractEvent, which needs to get updates pushed to it in real time.

Here's what my code looked like once the problem was fixed:

```
const { chains, provider, webSocketProvider } = configureChains(
  [chain],
  [alchemyProvider({ apiKey: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY as string, stallTimeout: 1_000, priority: 1 })],
);

const wagmiClient = createClient({
  autoConnect: true,
  provider,
  webSocketProvider
});
```
