### ISSUE TITLE
[BUG] Deeplinking on mobile wallets fails for signing transactions using wagmi

### ISSUE THREAD

**Issue by samkingco** [family/connectkit#35] opened 2022-10-27 13:10 UTC
**Describe the bug**

After connecting a wallet with `connectkit` on a mobile device, if you attempt to sign either a transaction or message using the wagmi hooks, then the wallet app does not open and you stay in the browser. You also don't get notifications to do anything so it looks like your app just hangs, but it's waiting for the signing to happen.

**To reproduce**

https://codesandbox.io/s/condescending-euler-sluziu

This also happens when using a custom wagmi client config instead of `getDefaultClient`.

Edit: An example in production can be found at https://drops.samking.studio, and the repo can be found [here](https://github.com/samkingco/sks-drops/tree/main/packages/app).

**Expected behavior**

When signing either a transaction or message using the wagmi hooks, the connected wallet app should open e.g. MetaMask mobile, or Rainbow etc. with the prompt to sign the transaction/message.

**Screenshots**

N/A

**Environment details**

iOS v16.1 and Safari
`wagmi@0.7.5`
`connectkit@0.2.0`

**Additional context**

If I just replace `connectkit` with `@rainbow-me/rainbowkit` then the wagmi hooks work perfectly on mobile.

**Comment by samkingco** [comment] 2022-11-08 03:03
Loving the new SIWE update, but this issue is still present on mobile wallets, even using the demo on the docs site. I’ve done a couple of implementations even on the latest wagmi and the issue still persists. Switching over to rainbow avoids the problem entirely, so I’m not sure if it’s something to do with the connectors setup in wagmi. I’d really prefer to use connectkit since I can get it to fit within my apps visual style a lot better. Any updates on what might be causing the issue?

**Comment by lochie** [comment] 2022-11-08 15:56
Hey @samkingco, this is something we're looking into. I was hoping to get this fix ready for the latest update but couldn't quite figure out exactly why this issue is occuring.

So far I've discovered that if you create your own wagmi client instead of using our `getDefaultClient` helper it seems to resolve itself – but from what we can tell the returned value is perfectly fine.

We will still be investigating this further and will let you know when we find a fix.

**Comment by cryptoman04** [comment] 2022-12-16 05:56
Hi @lochie checking in to see if there is a fix on the way. We are looking to integrate connectkit into our mobile application as well, but obviously this would be a blocker for us.

**Comment by cryptoman04** [comment] 2022-12-16 06:17
Additionally, would you be able to point me to the general area of where I should be looking at if I want to attempt to fix this? I can try and help fixing this issue as well.

**Comment by bouze** [comment] 2022-12-25 14:38
Hi, @lochie I too am having trouble with this issue.
Can you please let me know your current situation?

**Comment by lochie** [comment] 2023-01-30 05:02
Just an update, we've spent quite some time looking into this and still have yet to debug this one. We'll continue investigating as this is an important feature we need to get working.

**Comment by kobyle69** [comment] 2023-02-16 17:57
Any update yet? @lochie

**Comment by bcxbb** [comment] 2023-02-27 09:03
Is it possible to move createMessage out of the signIn function [here](https://github.com/family/connectkit/blob/79814fbfd51b1c1f58c2b9db32a9465934969876/packages/connectkit/src/siwe/SIWEProvider.tsx#L109)?

Lots of async activity before the actual signMessageAsync function can cause iOS deeplink to fail. 
https://wagmi.sh/react/prepare-hooks#ios-app-link-constraints

If you can change it to pass a message to the useSignMessage hook [here](https://github.com/family/connectkit/blob/79814fbfd51b1c1f58c2b9db32a9465934969876/packages/connectkit/src/siwe/SIWEProvider.tsx#L78) then that would reduce time from the user clicking the sign button to getting a sign prompt.

**Comment by shrugs** [comment] 2023-03-04 06:41
confirmed, deeplinking issue occurs on ios safari, even on initial walletconnect redirect. obviously hunting down this bug has occupied probably hundreds of collective developer-hours, but this behavior makes using connectkit for an app impossible at the moment.

based on what i have learned, links like this should be a true `<a>` tag with `target="_blank"` so they don't redirect from the page itself, and in the worst case just open a new tab that can be closed. doing a redirect in a div's click handler is what i believe is causing the behavior here.

separately, as @bcxbb mentioned, when proposing a tx or signature via walletconnect, no other async actions should be done in the button click handler, or a similar behavior will occur, in my experience

https://user-images.githubusercontent.com/1535001/222880024-7081a5e4-e516-4e90-bd4c-40e115848e54.mp4

**Comment by lochie** [comment] 2023-03-10 01:03
@shrugs i think what you're seeing here is different issue than this thread is talking about. The rnbwappdotcom.app.link page you're seeing is a fallback design of Rainbow when deeplinking doesn't work within their iOS redirect page for walletconnect, whilst what some people here are seeing is no deeplinking on signing requests _after_ connecting to a wallet on iOS.
Your suggestion to switch from a [window.location.href redirect](https://github.com/family/connectkit/blob/d659e9ce3641aa4858ab3b0e3dbe2725d4c7200d/packages/connectkit/src/components/Pages/MobileConnectors/index.tsx#L61) to an anchor with _blank might help in some cases, but will require the user to close that tab once deeplinking to the respective native app has occurred.

We've been looking the txn deeplinking issue on and off and haven't found the root of this issue yet, we're not sure if this is an issue on wagmi's end or connectkit's end, and since replicating seems to only be possible on a per-project level debugging is a bit complicated.

**Comment by pn-thedude** [comment] 2023-04-26 01:01
hey y'all, any update here? we are seeing the original issue -- deeplink occurs during initial connect but does not happen on sign in. happy to help if needed to get this complete. cc @lochie

**Comment by lekevicius** [comment] 2023-05-28 22:00
We're also seeing this issue on ConnectKit 1.4 and wagmi 1.0. Works with w3Modal.

**Comment by lochie** [comment] 2023-08-23 04:42
I'm unable to reproduce this now  so I believe this has been resolved with the WalletConnect 2.0 migration. If anyone can confirm this as resolved on their end with the latest version of ConnectKit I'd be keen to close this issue.

**Comment by lochie** [comment] 2023-08-29 02:39
Closing this issue as I believe it's resolved.

**Closed by lochie** 2023-08-29 02:39 UTC
Labels: bug
